### ISSUE TITLE
Works fine for iOS but breaking in PWA

### ISSUE THREAD

**Issue by thidasapankaja** [native-html/plugins#25]
First of all thanks for the library. I'm wondering does this supports PWA or just iOS and Web?

The same table renders correctly in the iOS device but getting error on Web (Chrome)

```
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Webshell`.
    at http://0.0.0.0:8080/vendors~main.646b02c2919a82ab84d1.js:137220:950
    at createFiberFromTypeAndProps (http://0.0.0.0:8080/vendors~main.646b02c2919a82ab84d1.js:137220:1131)
    at createFiberFromElement (http://0.0.0.0:8080/vendors~main.646b02c2919a82ab84d1.js:137220:1466)
    at reconcileSingleElement (http://0.0.0.0:8080/vendors~main.646b02c2919a82ab84d1.js:135458:714)
    at reconcileChildFibers (http://0.0.0.0:8080/vendors~main.646b02c2919a82ab84d1.js:135471:147)
    at reconcileChildren (http://0.0.0.0:8080/vendors~main.646b02c2919a82ab84d1.js:135708:22)
    at mountIndeterminateComponent (http://0.0.0.0:8080/vendors~main.646b02c2919a82ab84d1.js:135858:132)
    at beginWork$1 (http://0.0.0.0:8080/vendors~main.646b02c2919a82ab84d1.js:136147:101)
    at HTMLUnknownElement.callCallback (http://0.0.0.0:8080/vendors~main.646b02c2919a82ab84d1.js:132842:102)
    at Object.invokeGuardedCallbackDev (http://0.0.0.0:8080/vendors~main.646b02c2919a82ab84d1.js:132862:45)
```

The same code works correctly in iOS device, but breaking on Web.

**Comment by jsamr** [comment]
@thidasapankaja It breaks because of `react-native-webview` which has no support for Web. react-native-web is not an official project of React Native, and this library doesn't claim support for it. However, it might work if you replace  WebView from `react-native-webview` with [`react-native-web-webview`](https://github.com/react-native-web-community/react-native-web-webview), but I have never tried this library before. Tell me if it works out for you.

**Comment by thidasapankaja** [comment]
@jsamr Thanks a lot. sure. I'll check that and update here.

**Comment by jsamr** [comment]
You can also use a web alias :-) https://necolas.github.io/react-native-web/docs/?path=/docs/overview-getting-started--page#configuring-a-module-bundler

**Comment by jsamr** [comment]
@thidasapankaja Did that work out for you? I was thinking of implementing a custom "react-native-web-webview" thanks to [Ersatz](https://github.com/formidable-webview/ersatz), because Ersatz has a "backend" API that I could easily interface with react-dom.

**Comment by thidasapankaja** [comment]
Sorry about the delay in response. It didn't work for me.
In my case I used _dangerouslysetinnerhtml_ which were usable for my case.

Anyway, Thanks a lot

**Comment by jsamr** [comment]
@thidasapankaja I am actually implementing an alternative to `react-native-web-webview` ; would you be interested to test a pre-release?

**Comment by krini** [comment]
Did you create the react-native-web-webview pre-release?

**Comment by jsamr** [comment]
@krini Yes! A new package, `@formidable-webview/web` has been added to [Ubiquitous project](https://github.com/formidable-webview/ubiquitous). To enable this library after installing, you will have to tell webpack how to do it. [See this webpack config file](https://github.com/formidable-webview/ubiquitous/blob/ec7640cb1cd9499d444cdddc5111ef5801bfa86e/acceptance/web-app/webpack.config.js).
