### ISSUE TITLE
undefinded is not a function (near '...(0,_reactNativeRenderHtml.domNodeToHTMLString)...')

### ISSUE THREAD

**Issue by LimanASL** [native-html/plugins#28]
### Oath

I swear that I have completed these tasks before submitting:

- [ ] I have read the README
- [ ] I have checked that the issue has not been reported yet

##### React Native

```

```

##### Libraries

- react-native-render-html:
- @native-html/table-plugin:
- react-native-webview:

##### Devices

- Device 1 Samsung Galaxy A42
  * OS: Android 10.0
  * Diagnostic: reproduction
  * Environment:  development
- Device 2 simulator (iPhone 11)
  * OS:iOS 14.2
  * Diagnostic: reproduction
  * Environment:  development 

#### Description

![Simulator Screen Shot - iPhone 11 - 2020-12-21 at 14 58 02](https://user-images.githubusercontent.com/61727838/102748688-9f82ad80-439d-11eb-8999-cdfccc23e56f.png)

(Write your steps here:)

1. Type [npm install --save react-native-render-html] and [pod install] for install the plug-in , there are no error and the table of content display in WebView correctly
2. Close the metro terminal and re-run the simulator 
3. The error message appear if the HTML component rendering the html including the tag of<Table>

**Comment by LimanASL** [comment]
**Package Version as following:**

-      "react-native-render-html": "^5.0.1",
-     "@native-html/table-plugin": "^3.1.0",
-     "react-native-webview": "^10.10.2",

**Comment by jsamr** [comment]
@LimanASL I guess you had an outdated react-native-render-html version, is that it?

**Comment by LimanASL** [comment]
> @LimanASL I guess you had an outdated react-native-render-html version, is that it?

Yes.
