### ISSUE TITLE
i got error on back press please resolve it, thanks

### ISSUE THREAD

**Issue by aamiryameen** [native-html/plugins#29]
### Oath

I swear that I have completed these tasks before submitting:

- [ ] I have read the README
- [ ] I have checked that the issue has not been reported yet

##### React Native

```

```

##### Libraries

- react-native-render-html:
- @native-html/table-plugin:
- react-native-webview:

##### Devices

- Device 1 
  * OS: 
  * Diagnostic: 
  * Environment: 
- Device 2 
  * OS: 
  * Diagnostic: 
  * Environment: 

#### Description

(Write your steps here:)

1.
2.
3.

(Describe the expected outcome, and compare it to the observed outcome. You are
encouraged to join screenshots and screencasts, or pictures of the rendering
tree from debugging tools such as flipper)

#### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant
source code. When deemed appropriate, provide instructions to reproduce the
issue.)

**Comment by jsamr** [comment]
@aamiryameen Your report doesn't follow our template, so I am going to close. Likely an instance of a `react-native-screens` bug, see https://stackoverflow.com/a/63171413/2779871

**Comment by dzpt** [comment]
@jsamr the error is still there on `react-native-screens@2.18.1`
