### ISSUE TITLE
[iframe] Video always autoplay. How to disable autoplay?

### ISSUE THREAD

**Issue by luckybelle** [native-html/plugins#31]
I swear that I have completed these tasks before submitting:

- [ x ] I have read the README
- [ x ] I have checked that the issue has not been reported yet

##### React Native

System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 127.68 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh

  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 

##### Libraries

 
    react-native-render-html: 6.0.0-alpha.17
    @native-html/iframe-plugin: ^2.1.0
    react-native-webview: ^11.2.3

#### Description
When render iframe The Vdo is auto play. How to disable autoplay video?

This is my code 
### 
    const IframeRenderer = (props) => {
        const iframeProps = useHtmlIframeProps(props);
        // Do customize the props here; wrap with your own container...
        return iframeProps ? <HTMLIframe {...iframeProps} /> : null;
    };

    IframeRenderer.model = iframeModel;

    const renderers = {
        iframe: IframeRenderer
    }

   const html = '<iframe width="420" height="315" src="https://storage.googleapis.com/demo-coj/exhibition/17bc59130550baf741080ddaf18e8154.mp4"></iframe>'

    return <RenderHTML
                                renderers={renderers}
                                WebView={WebView}
                                renderersProps={{
                                    iframe: {
                                        scalesPageToFit: true,
                                        autoplay: false,
                                        webViewProps: {
                                            autoplay: false,
                                            mediaPlaybackRequiresUserAction: true
                                        }
                                    }
                                }}
                                source={{html: html}}
                                contentWidth={width}/>

**Comment by jsamr** [comment]
@luckybelle The issue you are reporting is not inherent to the Iframe plugin, but rather to using a `WebView` component with a `src` referring to a video file instead of HTML file.

You can reproduce the issue very easily with `react-native-webview` alone:

```jsx
<WebView
  mediaPlaybackRequiresUserAction
  source={{
    uri:
      "https://storage.googleapis.com/demo-coj/exhibition/17bc59130550baf741080ddaf18e8154.mp4",
  }}
/>;
```

I suggest either:

- Report a bug in [`react-native-webview`](https://github.com/react-native-webview/react-native-webview) issue tracker
- Create a custom iframe renderer which conditionally uses [`react-native-video`](https://github.com/react-native-video/react-native-video) library to render when src is a media URL. Below is a quickstarter sample:

```jsx
import * as React from 'react';
import WebViewIframeRenderer, {iframeModel} from '@native-html/iframe-plugin';

const IframeRenderer = function (props) {
  const src = props.tnode.attributes.src || '';
  if (src.match(/\.mp4$/)) {
    return /* An element based on react-native-video */;
  }
  // Defaults to the WebView-based iframe renderer
  return <WebViewIframeRenderer {...props} />;
};

IframeRenderer.model = iframeModel;
```
And of course, you'll nee to add it to `renderers.iframe` prop.
