### ISSUE TITLE
[iframe] "scalesPageToFit=true" not zooming out

### ISSUE THREAD

**Issue by Naxus28** [native-html/plugins#32]
The iframe is not zooming out when it exceeds the width of the view. You can see a screenshot of the iframe on ios and android emulators below:
![Screen Shot 2021-03-24 at 2 51 05 PM](https://user-images.githubusercontent.com/5386170/112367775-bbedf900-8cb0-11eb-87fa-f93fa1f9f5e9.png)

These are the config obj and the returned component:

```
const htmlConfig = {
    renderers: {
      iframe,
    },
    WebView,
    defaultWebViewProps: {
      containerStyle: {
        width: contentWidth - 40,
      },
    },
    ignoredTags: IGNORED_TAGS,
    renderersProps: {
      iframe: {
        scalesPageToFit: true,
      },
    },
    tagsStyles: {
      iframe: {
        alignSelf: 'center',
      },
    },
  };

  return (
    <ScrollView>
      <HTML
        source={{html: content}}
        contentWidth={contentWidth}
        {...htmlConfig}
      />
    </ScrollView>
  );

```

**Comment by jsamr** [comment]
@Naxus28 Thanks for your submission! To help you out I would need to know:

- the version of the plugin 
- version of react-native-render-html
- version of react-native-webview
- an HTML snippet allowing me to reproduce the issue locally

thanks!

**Comment by Naxus28** [comment]
Hey there @jsamr. Other than that everything works smoothly. Thanks for the library. Here you go:
• the version of the plugin: "@native-html/iframe-plugin": "^1.1.2",
• version of react-native-render-html: "react-native-render-html": "^5.0.1",
• version of react-native-webview: "react-native-webview": "^11.2.5",
• an HTML snippet allowing me to reproduce the issue locally: 
```
const iframes = `
  <section>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/mNz6eHfsESQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <p style="text-align:center;"><em>Skeletor's Best Insults; enjoy</em></p>
  </section>
`;
```
Please let me know if this works.

Thanks!

**Comment by jsamr** [comment]
@Naxus28 You should use `contentWidth` prop of `react-native-render-html`. Here is the fix:

```patch
@@ -18,11 +18,6 @@ export default function App() {
       iframe,
     },
     WebView,
-    defaultWebViewProps: {
-      containerStyle: {
-        width: contentWidth - 40,
-      },
-    },
     ignoredTags: IGNORED_TAGS,
     renderersProps: {
       iframe: {
@@ -38,7 +33,7 @@ export default function App() {
 
   return (
     <ScrollView style={styles.container}>
-      <HTML source={{html}} {...htmlConfig} />
+      <HTML source={{html}} contentWidth={contentWidth - 40} {...htmlConfig} />
     </ScrollView>
   );
 }
```

Tell me if that works out for you.

**Comment by Naxus28** [comment]
Nice! That fixed it. I have to keep `defaultWebViewProps.containerStyle.width` though because I am also supporting tables, which won't display if `defaultWebViewProps.containerStyle.width` is not set. Not sure that is the desired behavior but that is how it is working now.

**Comment by jsamr** [comment]
@Naxus28 interesting; if you find the time for a reproduction I'll welcome it! Closing now as your issue looks addressed :-)
