### ISSUE TITLE
[iframe-plugin] Add an option to add headers to the webview

### ISSUE THREAD

**Issue by emmguyot-adscom** [native-html/plugins#38]
### Oath

I swear that I have completed these tasks before submitting:

- [X ] I have read the README
- [X ] I have checked that the feature request has not been reported yet
- [X ] I have prefixed this issue title with the plugin suffix (e.g: [iframe-plugin]) depending on the affected plugin

### Decision table

- [X ] The change I am requesting is not concerning performance
- [X ] The change I am requesting is not concerning code style, compliance with
  official guidelines and recommendations, third-party deprecations,
  refactoring or development tooling

### Feature

The iframe plugin sets the _source_ of the webview with either html or uri, but there is no way to set the headers attribute when using uri.
Setting the headers might be useful and, in my case, it is a must have to display some Youtube Videos (not every one requires it).

My case : 
I have an html that includes one or more iframe tags with src to Youtube (sample : https://www.youtube.com/embed/o-Wr61tBX7c). Without the header set in the source property, the video isn't displayed, but if I set it, it does.
That's why I need a way to set it.

This would be useful in both version 5.x and 6.x

**Comment by jsamr** [comment]
@emmguyot-adscom PRs are welcomed!
