### ISSUE TITLE
[table-plugin] Android app (expo go and production) crashes for certain html content

### ISSUE THREAD

**Issue by janrop** [native-html/plugins#43]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the README
- [x] I have checked that the issue has not been reported yet
- [x] I have prefixed this issue title with the plugin suffix (e.g: [iframe-plugin]) depending on the affected plugin

##### React Native

```
Need to install the following packages:
  expo-env-info
Ok to proceed? (y) y

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.0
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 17.5.0 - ~/.nvm/versions/node/v17.5.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.4.1 - ~/.nvm/versions/node/v17.5.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 14.1/14B47b - /usr/bin/xcodebuild
    npmPackages:
      expo: ~47.0.3 => 47.0.3 
      react: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
    npmGlobalPackages:
      expo-cli: 6.0.8
    Expo Workflow: managed
```

##### Devices

- Device 1 physical (Samsung Galaxy S10)
  * OS: Android 12
  * Diagnostic: reproduction
  * Environment: development and production

### Reproduction

https://github.com/janrop/react-native-table-renderer-android-crash-repro

#### Description

(Write your steps here:)

1. Open the repro on a physical android device
2. The app crashes

Does it have to do with the amount of tables?

#### Reproducible Demo

https://github.com/janrop/react-native-table-renderer-android-crash-repro

**Comment by NeoPCl** [comment]
Any fixes here? Happens to me to. Only thing I see via sentry that it is a SIGSEGV: Segfault.

> system
    exception
        stack-trace
            frame
                function
                    androidCreateRawThreadEtc
            frame
                function
                    android::Thread::_threadLoop

**Comment by janrop** [comment]
After some more trial and error, this seems to fix it, so its probably not a native-html problem, but rather only related to WebView

```javascript
renderersProps: {
    webViewProps: {
        style: {
            opacity: 0.99,
            overflow: 'hidden'
        },
    },
},
```
